repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: fix-byte-order-marker

      - id: check-json
      - id: check-json5
      - id: check-yaml
      - id: check-toml
      - id: check-xml

      - id: check-case-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/MuXiu1997/pre-commit-hooks
    rev: v0.2.0
    hooks:
      - id: yamlfmt
      - id: tombi-lint
      - id: tombi-format
